Repository amirmsoltani/denanova, pull requests merged in 2022-09, with the labels that each got.

#35 Delete post
  pages/admin/addPost.tsx
  pages/admin/companies.tsx
  pages/admin/products.tsx
  pages/contactUs.tsx
  pages/servicesUs.tsx
  prisma/dev.db
Labels: bug

#37 feat: delete post in companies and products is done.
  layout/adminWrapper.tsx
  package.json
  pages/_app.tsx
  pages/admin/addPost.tsx
  pages/admin/companies.tsx
  pages/admin/index.ts
  pages/admin/products.tsx
  yarn.lock
Labels: feat, admin

#38 feat: admin contact us messages back end
  .gitignore
  package.json
  pages/admin/messages.tsx
  yarn.lock
Labels: feat, admin

#40 feat: add create user endpoint
  pages/api/admin/login.ts
  pages/api/admin/user/[key].ts
Labels: feat

#41 Update post
  package.json
  pages/admin/addPost.tsx
  pages/admin/companies.tsx
  pages/api/admin/post/[id].ts
  yarn.lock
Labels: feat, admin

#47 feat: change model and api post for company issue
  pages/api/admin/post/[id].ts
  pages/api/admin/post/index.ts
  prisma/migrations/20220908132018_company/migration.sql
  prisma/schema.prisma
Labels: feat, admin

#49 feat: all backend
  pages/admin/addPost.tsx
  pages/admin/files.tsx
  pages/admin/login.tsx
  pages/admin/messages.tsx
  pages/agencies.tsx
  pages/api/admin/file/[id].ts
  pages/api/admin/post/[id].ts
  pages/index.tsx
  pages/product/[id].tsx
  pages/products.tsx
  yarn.lock
Labels: feat, origin

#50 Company
  components/tableCompany.tsx
  components/tableMessage.tsx
  components/tablePost.tsx
  layout/Header.tsx
  layout/warpper.tsx
  pages/admin/addPost.tsx
  pages/admin/companies.tsx
  pages/admin/login.tsx
  pages/admin/messages.tsx
  pages/agencies.tsx
  pages/api/admin/file/[id].ts
  pages/api/admin/post/[id].ts
  pages/contactUs.tsx
  pages/index.tsx
  pages/product/[id].tsx
  pages/products.tsx
  pages/servicesUs.tsx
  public/logo.ico
  public/map.png
  public/sliderHomeIMG1.jpg
  public/sliderHomeIMG2.jpg
  public/sliderSerIMG1.jpg
  public/sliderSerIMG2.jpg
  public/sliderSerIMG3.jpg
Labels: feat, origin

#51 Images
  layout/warpper.tsx
  pages/admin/addPost.tsx
  pages/admin/companies.tsx
  pages/admin/files.tsx
  pages/admin/index.ts
  pages/admin/login.tsx
  pages/admin/products.tsx
  pages/agencies.tsx
  pages/contactUs.tsx
  pages/index.tsx
  pages/product/[id].tsx
  pages/products.tsx
  pages/servicesUs.tsx
  public/company1.jpg
  public/company2.jpg
  public/company3.jpg
  public/company4.jpg
  public/company5.jpg
  public/ferdowsiUni1.jpg
  public/ferdowsiUni1.webp
  public/ferdowsiUni2.jpg
  public/ferdowsiUni2.webp
  public/ferdowsiUni3.jpg
  public/ferdowsiUni3.webp
  public/imgProduct1.jpg
  public/imgProduct2.jpg
  public/imgProduct3.jpg
  public/imgProduct4.jpg
  public/map.png
  public/sliderHomeIMG1.jpg
  public/sliderHomeIMG2.jpg
  public/sliderSerIMG1.jpg
  public/sliderSerIMG2.jpg
  public/sliderSerIMG3.jpg
Labels: bug, feat
